[WIP] Parallel experiment mock IQ backend (#807)
* Test Changes

* Test Changes

* Added multiple qubit support in the base class

* added function '_expand_probability'  and description

Added function '_expand_probability' which get the number of qubit and the probability dictionary and extend the probability dictionary to include degeneracy of probability 0.
In addition, I added description to functions.

* Update mock_iq_backend.py

* added description after conflicts

* Changed Drag to support new design - need to change the probability from dictionary to array

* made changes due to the review

* the new backend support the test in test_drag.py

* fixed code per review and added support for variety of tests

* The iteration on the output string is now from LSB to MSB

* removed abstract method and added callable

* test_drag.py is working with the new design of mock iq backend

* test_rabi and test_drag are working - still have comments in the code and the getting error for analysis

Example for analysis failure:
Analysis callback failed [Analysis ID: c5cbddf663384fa48990fd992eed6777]:
  File "C:\Users\014780756\Documents\github_IQ_level_1_measurement\qiskit_experiments\data_processing\data_processor.py", line 238, in _data_extraction
    raise DataProcessorError(
Analysis callback failed [Analysis ID: c5cbddf663384fa48990fd992eed6777]:
qiskit_experiments.data_processing.exceptions.DataProcessorError: 'The input key fail_key was not found in

* deleted commented line and passed black + pylint

* tests updates + unittest (need to be deleted)

* rabi+drag are working

* added edit as @yaelbh suggested (partly)

* More editing per the review

* black + pylint passs. Have problem with convergence in test_ramsey_xy

The problem in the test "test_ramsey_xy.py" is that the curve fitting function doesn't converge. Looking into the data I see that while the values are different for the counts, the statistics is the same. I think it's because in the new MockIQBackend  I use multinomial distribution function instead of Bernoulli's.

* code passed black (version 22.1.0)

* start of changes in spectroscopy and half angle

* Almost all tests are working - found a bug where cluster centers are exchanged

* pylint

* black + added examples to MockIQBackend

* fixed grammar mistakes

* Update mock_iq_backend.py

* fixed bug in probability calculation of ramseyXY

* changed _probability_dict_to_probability_array

* Created new file 'mock_iq_helpers' and changed mock iq backend

* black + lint

* black + lint

* black + pylint

* Added type hinting and added allocation of memory to the list

* Added class of mock IQ test  for multiple qubits

* Changes after Eli Review - Part 1

* black

* test_drag.py updated

* test_rabi.py updated

* test added for data generation

* final touches

documentation and efficiency.

* fixed test (changed centers)

* Merged ResonatorSpectroscopy into Spectroscopy

* bug fix

* black fix

* Parrallel experiment template (WIP)

* changed how generated data is generating data (work in progress)

* generate data - need to fix bug for qubits index

* Parallel experiment backend working and past test are working

* mock_iq_backend black + pylint

* mock_iq_helpers.py - updated +black + lint

added property to MockIQParallelExperimentHelper

* fixed documantation in _draw_iq_shots

* Added tests and parallel experiment circuit splitter

* Helpers can split parallel experiment circuit + tests for parallel experiment

* documentation + black + lint

* changed  qubit reference due to deprecation warning

* Editing after Yael review part 1.

* Editing after @yaelbh review part 2

* black + lint

* black + lint

* part 3 final

* removed optional from the __init__ of 'MockIQParallelExperimentHelper' and added optional to the helper in the MockIQParallelBackend

* Updated tests

* fixed bug in MockIQParallelBackend

* last fixes. Added getter and setter for 'experiment_helper'

* Fixed comments in `_parallel_draw_iq_shots`

* String are now f-strings

* changed string format to f-strings in mock_iq_helpers

* added `# pylint: disable=no-member` to the code

* Update test_rabi.py