Turn off parallel docs build and pin dependencies (#1097)
### Summary

The docs build is suddenly breaking with 

```
  File "/home/runner/work/qiskit-experiments/qiskit-experiments/.tox/docs-parallel/lib/python3.8/site-packages/sphinx/util/parallel.py", line 126, in _join_one
    raise SphinxParallelError(*result)
sphinx.errors.SphinxParallelError: sphinx.errors.ExtensionError: Unable to find kernel (exception: No such kernel named python3)
```

Turning off the parallel flag didn't solve the problem, but pinning
`ipykernel` and `jupyter-client`, both of which put out new releases
yesterday, solved the problem. I'm keeping the parallel flag off since
it tends to cause issues until this compatibility issue is resolved.